# settings.yml
foundation: Space Value Chain (SVC)
url: http://127.0.0.1:8000
title: Space Value Chain (SVC)
description: Visualizing the global Space Value Chain ecosystem.

colors:
  color1: "#006BCC"
  color2: "#FF00AA"
  color3: "#6095D6"
  color4: "#002A51"
  color5: "#016BCC"
  color6: "#002A51"
  color7: "#B4DBFF"

grid_items_size: medium

header:
  logo: "logos/svc-logo.svg" # Replace
  links:
    github: "https://github.com/JayCuthrell/svc.fudge.org"

footer:
  logo: "logos/svc-footer-logo.svg" # Replace
  links:
    homepage: "https://github.com/JayCuthrell/svc.fudge.org"

groups:
  - name: Orbital Infrastructure
    categories:
      - Orbital Compute, Data Processing & AI
      - Cloud Extension & Satellite Connectivity
      - Hardware, Manufacturing & Radiation Hardening
  - name: Operations & Exploration
    categories:
      - Space Logistics, Servicing & Safety
      - Sensing, Imagery & Domain Awareness
      - Lunar Exploration & Off-World Hosting
  - name: Governance
    categories:
      - Government & Regulatory Agencies